name = "dryvest"
main = "worker.ts"
compatibility_date = "2024-11-12"

[assets]
directory = "app/dist"
binding = "ASSETS"

[build]
command = "npm --prefix app install && ln -sfn app/node_modules node_modules && npm --prefix app run build"

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "HOOKS"
# HOOKS KV namespace (production + preview). Update preview ID if needed.
id = "caf4e19f1388423fade84340c27a929c"
preview_id = "caf4e19f1388423fade84340c27a929c"

[[d1_databases]]
binding = "DRYVEST_DB"
database_name = "dryvest"
# Replace with the production database ID after provisioning
database_id = "00000000-0000-0000-0000-000000000000"

[durable_objects]
bindings = [
  { name = "DRYVEST_ANALYTICS", class_name = "DryvestAnalyticsDO" }
]

[[migrations]]
tag = "2025-09-28-analytics"
new_classes = ["DryvestAnalyticsDO"]
