name = "dryvest"
main = "worker.ts"
compatibility_date = "2024-11-12"

[assets]
directory = "app/dist"
binding = "STATIC_ASSETS"

[build]
command = "npm --prefix app install && ln -sfn app/node_modules node_modules && npm --prefix app run build"

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "HOOKS"
# HOOKS KV namespace (production + preview). Update preview ID if needed.
id = "caf4e19f1388423fade84340c27a929c"
preview_id = "caf4e19f1388423fade84340c27a929c"

[ai]
binding = "AI"

[[r2_buckets]]
binding = "DRYVEST_R2"
bucket_name = "dryvest"

[[d1_databases]]
binding = "DRYVEST_DB"
database_name = "dryvest"
database_id = "7e33620c-2a5a-4e89-9f18-29ccd1cbafb8"

[durable_objects]
bindings = [
  { name = "DRYVEST_ANALYTICS", class_name = "DryvestAnalyticsDO" }
]

[[migrations]]
tag = "2025-09-28-analytics"
new_classes = ["DryvestAnalyticsDO"]

[browser]
binding = "BROWSER"
