import { useState } from 'react';
import { Download, Loader2 } from 'lucide-react';
import { exportToPDF, getPreviewContent, generateTitle } from '../lib/pdf-export';
import type { BriefContext } from '../lib/schema';

interface PDFExportButtonProps {
  context: BriefContext;
  venue?: string;
  decisionMaker?: string;
  disabled?: boolean;
}

export function PDFExportButton({
  context,
  venue = 'Investment Committee',
  decisionMaker = 'Board of Trustees',
  disabled = false
}: PDFExportButtonProps) {
  const [isExporting, setIsExporting] = useState(false);
  const [disclaimerAccepted, setDisclaimerAccepted] = useState(false);
  const [showDisclaimer, setShowDisclaimer] = useState(false);

  const handleExport = async () => {
    if (!disclaimerAccepted) {
      setShowDisclaimer(true);
      return;
    }

    setIsExporting(true);

    try {
      const content = getPreviewContent();
      const title = generateTitle(context);

      await exportToPDF({
        title,
        content,
        venue,
        decisionMaker,
        context,
      });

    } catch (error) {
      console.error('PDF export failed:', error);
      alert(error instanceof Error ? error.message : 'PDF export failed. Please try again.');
    } finally {
      setIsExporting(false);
    }
  };

  const acceptDisclaimer = () => {
    setDisclaimerAccepted(true);
    setShowDisclaimer(false);
    handleExport();
  };

  return (
    <>
      <button
        onClick={handleExport}
        disabled={disabled || isExporting}
        className="inline-flex items-center gap-2 rounded-md bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
      >
        {isExporting ? (
          <Loader2 size={16} className="animate-spin" />
        ) : (
          <Download size={16} />
        )}
        {isExporting ? 'Generating PDF...' : 'Export PDF'}
      </button>

      {showDisclaimer && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50">
          <div className="max-w-md rounded-lg bg-white p-6 shadow-xl">
            <h3 className="mb-4 text-lg font-semibold text-gray-900">
              Export Disclaimer
            </h3>
            <div className="mb-4 space-y-3 text-sm text-gray-700">
              <p>
                This investment brief is generated by Dryvest, an experimental tool from
                Ethical Capital Labs for educational and research purposes.
              </p>
              <p>
                <strong>Important:</strong> This content does not constitute investment advice.
                Please consult with qualified professionals before making investment decisions.
              </p>
              <p>
                By proceeding, you acknowledge that this content is for informational
                purposes only and should not be relied upon for investment decisions.
              </p>
            </div>
            <div className="flex gap-3 justify-end">
              <button
                onClick={() => setShowDisclaimer(false)}
                className="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-100 rounded-md hover:bg-gray-200 transition-colors"
              >
                Cancel
              </button>
              <button
                onClick={acceptDisclaimer}
                className="px-4 py-2 text-sm font-medium text-white bg-indigo-600 rounded-md hover:bg-indigo-700 transition-colors"
              >
                I Understand, Export PDF
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}